
spring.application.name=workflow

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://adminn:adminn@audi.gbtslpg.mongodb.net/workflow?retryWrites=true&w=majority
spring.mongodb.uri=mongodb+srv://adminn:adminn@audi.gbtslpg.mongodb.net/workflow?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true  

# JWT
jwt.secret=workflow_secret_key_change_in_production_must_be_at_least_32_chars
jwt.expiration=86400000