spring.application.name=workflow

# MongoDB
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/workflow_db
spring.data.mongodb.auto-index-creation=true

# JWT
jwt.secret=workflow_secret_key_change_in_production_must_be_at_least_32_chars
jwt.expiration=86400000
