
spring.application.name=workflow

# MongoDB
spring.data.mongodb.uri=mongodb+srv://vagnermerlinbonillas_db_user:21_12_2001Vagner@workflowdb.0a7ypte.mongodb.net/workflow?retryWrites=true&w=majority&appName=workflowdb
spring.mongodb.uri=mongodb+srv://vagnermerlinbonillas_db_user:21_12_2001Vagner@workflowdb.0a7ypte.mongodb.net/workflow?retryWrites=true&w=majority&appName=workflowdb
spring.data.mongodb.database=workflow
spring.mongodb.database=workflow
spring.data.mongodb.auto-index-creation=true

# JWT
jwt.secret=workflow_secret_key_change_in_production_must_be_at_least_32_chars
jwt.expiration=86400000
